### ISSUE TITLE
C3 Chart - Y Axis goes negative.

### ISSUE THREAD

**Issue by ddeuchert** [FollettSchoolSolutions/perfmon4j-reports#26]
I see a lot of times where the C3 y axis is negative, even though none of the data values are less than 0.  

I found this answer online that seems to suggest a way to correct it: http://www.codeotel.com/CmVVkkUkPX/c3-chart-shows-negative-ylabels.html

![image](https://cloud.githubusercontent.com/assets/6036847/8826830/caa13ab2-304e-11e5-8aa9-b23663b5802a.png)

**Comment by cdeuchert** [comment]
The issue has been resolved with fix/Scale_Y_Axis.
