### ISSUE TITLE
Rescale Y axis on Zoom.

### ISSUE THREAD

**Issue by ddeuchert** [FollettSchoolSolutions/perfmon4j-reports#34]
When you zoom in to a subsection of the chart, the y-axis remains scaled for the total data set.  It would be better if the y-axis would scale based only on the selected range.

This C3 issue seems to indicate it is an option with v4.0 of C3:
   https://github.com/masayuki0812/c3/issues/98

![image](https://cloud.githubusercontent.com/assets/6036847/8880816/271bdcee-3201-11e5-901b-03db2dbbccf5.png)

**Comment by cdeuchert** [comment]
This was finished as part of the Chart Label Enhancements pull request.
