### ISSUE TITLE
DB upgrade for SSO.

### ISSUE THREAD

**Issue by Andrewsh86** [FollettSchoolSolutions/perfmon4j-reports#60]
Create a User Table that stores the user's name, github id, and indexes on the github id.
Add a field to the charts table (and dashboard if it has been implemented) that corresponds to a user.  Make this field nullable and existing charts should have null for this field. Fields with null users are viewable by all users.

**Comment by pizzaboy314** [comment]
@Rayfucious @ddeuchert 
I believe this solution to this is to wipe the live DB when we actually deploy to live. I think removing the MySQL cartridge in OpenShift and readding it will accomplish this.

**Comment by pizzaboy314** [comment]
yeah, we're just going to wipe it.
