### ISSUE TITLE
Id column In DataSource is not auto-incrementing/Sequential

### ISSUE THREAD

**Issue by RRobey** [FollettSchoolSolutions/perfmon4j-reports#76]
Datasources that are saved are currently getting random, unique values.  We were unable to determine the cause of this.  It should be assigning unique, sequential values to datasource.  Not a big deal, but something to consider.

**Comment by pizzaboy314** [comment]
@Rayfucious @ddeuchert 
I believe this is how hibernate works? Is this actually considered a bug?
